import Bg_Banner from '../../assets/images/outros/bg_banner.jpg';
import Bg_SobreNos from '../../assets/images/outros/bg_sobreNos.jpg';
import Bg_FaleConosco from '../../assets/images/outros/bg_faleConosco.jpg';
import Horus from "../../assets/images/outros/horus.png";

const Style = () => {
    return {
        home: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#f5f5f5',
            margin: '0',
        },
        buttonsNavbar: {
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-around',
            width: '100%',
            margin: '0',
            backgroundColor: '#513B28'
        },
        buttonGroup: {
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            width: '70%',
        },
        buttonNavbar: {
            backgroundColor: 'transparent',
            color: '#fff',
            textDecoration: 'none',
            boxShadow: 'none',
            '&:hover': {
                boxShadow: 'none',
                backgroundColor: '#735438',
            },
            borderRadius: '0',
            height: '50px',
            margin: '0 10px',
        },
        dividerNavbar: {
            backgroundColor: '#fff',
            margin: '0 10px',
        },
        login: {
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            width: '240px',
        },
        buttonLogin: {
            backgroundColor: '#c08c5e',
            color: '#fff',
            textDecoration: 'none',
            '&:hover': {
                boxShadow: 'none',
                backgroundColor: '#735438',
            },
        },
        banner: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            width: '100%',
            height: '700px',
            position: 'relative',
            backgroundImage: `url(${Bg_Banner})`,
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            backgroundRepeat: 'no-repeat',
            overflow: 'hidden',
            '&::before': {
                content: '""',
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: '100%',
                background: 'rgba(0, 0, 0, 0.65)', 
                zIndex: 0,
            },
        },
        logo: {
            backgroundImage: `url(${Horus})`,
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            backgroundRepeat: 'no-repeat',
            width: '350px',
            height: '450px',
            position: 'relative',
            zIndex: 1,
            margin: '0 auto', 
            display: 'block',
        },
        subtitle: {
            color: '#BF8B5E',
            fontSize: '24px',
            fontWeight: 'bold',
            textAlign: 'center',
            zIndex: 1,
            position: 'relative',
            marginTop: '20px',
            marginBottom: '20px', 
        },
        container: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            width: '100%',
            padding: '20px',
            backgroundColor: '#f5f5f5',
        },
        title: {
            color: '#513B28',
            fontSize: '24px',
            fontWeight: 'bold',
            textAlign: 'center',
            marginBottom: '10px',
        },
        divider: {
            backgroundColor: '#513B28',
            width: '250px',
            height: '3px',
            marginBottom: '20px',
        },
        textServices: {
            color: '#666',
            fontSize: '18px',
            textAlign: 'center',
            marginBottom: '20px',
            width: '70%',
        },
        services: {
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            width: '100%',
            flexWrap: 'wrap',
        },

        containerSobre: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            width: '100%',
            backgroundColor: '#ECECEC',
        },

        separator: {
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            width: '100%',
            padding: '20px',
            backgroundColor: '#ECECEC',
            boxSizing: 'border-box',
        },
        sobre: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'flex-start',
            justifyContent: 'flex-start',
            width: '60%',
            padding: '20px',
            backgroundColor: '#ffffff',
            borderRadius: '8px',
            boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
        },
        imgSobre: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            width: '40%',
            backgroundColor: '#ffffff',
        },
        bgSobreNos: {
            backgroundImage: `url(${Bg_SobreNos})`,
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            backgroundRepeat: 'no-repeat',
            width: '100%',
            height: '300px', 
            borderRadius: '0 8px 8px 0',
        },
        text: {
            color: '#666',
            fontSize: '18px',
            textAlign: 'left',
            marginBottom: '20px',
            lineHeight: '1.6',
        },
        team: {
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            width: '80%',
            flexWrap: 'wrap',
        },
        containerFale: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            width: '100%',
            padding: '20px',
            backgroundColor: '#ECECEC',
        },
        imgFale: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            width: '40%',
            backgroundColor: '#ffffff',
        },
        bgFaleConosco: {
            backgroundImage: `url(${Bg_FaleConosco})`,
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            backgroundRepeat: 'no-repeat',
            width: '100%',
            height: '400px',
            borderRadius: '8px 0 0 8px',
        },
        faleConosoco: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'flex-start',
            justifyContent: 'flex-start',
            width: '60%',
            padding: '20px',
            backgroundColor: '#ffffff',
            borderRadius: '8px',
            boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
        },
        input: {
            width: '100%',
            marginBottom: '20px',
        },
        button: {
            width: '100%',
            backgroundColor: '#c08c5e',
            color: '#fff',
            '&:hover': {
                backgroundColor: '#735438',
            },
        },
        containerContato: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            width: '100%',
            padding: '20px',
            backgroundColor: '#f5f5f5',
        },
        contactBox: {
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'flex-start',
            width: '100%',
            padding: '10px',
            boxSizing: 'border-box',
        },
        contact: {
            color: '#666',
            fontSize: '18px',
            fontWeight: 'bold',
            width: '100px',
        },
        item: {
            color: '#666',
            fontSize: '16px',
            width: '100%',
            marginLeft: '10px',
        },
    };
};

export const style = () => Style();

